export const quotes = [
    "Positivity always wins…Always. Gary Vaynerchuk",
    "Keep looking up… that’s the secret of life. Charlie Brown",
    "The first step is you have to say that you can. Will Smith",
    "Once you choose hope, anything’s possible. Christopher Reeve",
    "You can, you should, and if you’re brave enough to start, you will. Stephen King",
    "The best way to predict the future is to create it. Abraham Lincoln",
    "The best is yet to be. Robert Browning",
    "We can change our lives. We can do, have, and be exactly what we wish. Tony Robbins",
    "A problem is a chance for you to do your best. Duke Ellington",
    "The most important thing is to look ahead. The past is your anchor. Maxime Lagacé",
    "Positive anything is better than negative nothing. Elbert Hubbard",
    "Problems are not stop signs, they are guidelines. Robert Schuller",
    "I am thankful to all who said no to me. It is because of them that I’m doing it myself. Albert Einstein",
    "Try to be a rainbow in someone’s cloud. Maya Angelou",
    "Be thankful for what you have; you’ll end up having more. Oprah Winfrey",
    "Miracles happen to those who believe in them. Bernhard Berenson Click to tweet",
    "With the new day comes new strength and new thoughts. Eleanor Roosevelt",
    "Victory is in having done your best. If you’ve done your best, you’ve won. Billy Bowerman",
    "Wherever you are, and whatever you do, be in love. Rumi",
    "Believe deep down in your heart that you’re destined to do great things. Joe Paterno",
    "In the end, everything will be okay. If it’s not okay, it’s not yet the end. Fernando Sabino",
    "Mix a little foolishness with your serious plans. It is lovely to be silly at the right moment. Horace",
    "One small positive thought can change your whole day. Zig Ziglar",
    "Joy is not in things; it is in us. Richard Wagner",
    "One person can make a difference, and everyone should try. John F. Kennedy Click to tweet",
    "How high you fly is derived from how big you think. Robin Sharma Click to tweet",
    "Attitude is a little thing that makes a big difference. Winston Churchill",
    "Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you. Mary Lou Retton",
    "Wherever you go, no matter what the weather, always bring your own sunshine. Anthony J. D’Angelo",
    "Live as if your prayers are to be answered. Unknown",
    "Be the light in the dark, be the calm in the storm and be at peace while at war. Mike Dolan",
    "I ask not for a lighter burden, but for broader shoulders. Jewish proverb",
    "Arise, awake and stop not till the goal is reached. Swami Vivekananda",
    "There are far, far better things ahead than anything we leave behind. C. S. Lewis Click to tweet",
    "Life has no limitations, except the ones you make. Les Brown",
    "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all. Dale Carnegie",
    "The less you respond to negative people, the more positive your life will become. Paulo Coelho",
    "We must embrace pain and burn it as fuel for our journey. Kenji Miyazawa",
    "Little minds are tamed and subdued by misfortune; but great minds rise above them. Washington Irving",
    "I have decided to be happy, because it’s good for my health. Voltaire",
    "Think big thoughts but relish small pleasures. H. Jackson Brown",
    "Change your thoughts and you change your world. Norman Vincent Peale Click to tweet",
    "It doesn’t matter how slow you go, as long as you don’t stop. Confucius",
    "Choose to be optimistic, it feels better. Dalai Lama",
    "Even though you’re fed up, you gotta keep your head up. Tupac Shakur",
    "Write it on your heart that every day is the best day in the year. Ralph Waldo Emerson",
    "Always bear in mind that your own resolution to succeed is more important than any other one thing. Abraham Lincoln",
    "That which doesn’t kill us makes us stronger. Friedrich Nietzsche",
    "Always turn a negative situation into a positive situation. Michael Jordan",
    "I’ve failed over and over and over again in my life. And that is why I succeed. Michael Jordan",
    "It makes a big difference in your life when you stay positive. Ellen DeGeneres",
    "The positive thinker sees the invisible, feels the intangible, and achieves the impossible. Winston Churchill",
    "The pessimist sees difficulty in every opportunity. The optimist sees the opportunity in every difficulty. Winston Churchill",
    "Dwell on the beauty of life. Watch the stars, and see yourself running with them. Marcus Aurelius",
    "Never let your head hang down. Never give up and sit down and grieve. Find another way. And don’t pray when it rains if you don’t pray when the sun shines. Richard M. Nixon",
    "Believe you can and you’re halfway there. Theodore Roosevelt",
    "The future belongs to those who believe in the beauty of their dreams. Eleanor Roosevelt",
    "If you don’t like something change it. If you can’t change it, change your attitude about it. Don’t complain. Maya Angelou",
    "Believe that life is worth living and your belief will help create the fact. William James",
    "If opportunity doesn’t knock, build a door. Milton Berle",
    "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. Thomas Edison",
    "There is a sense that things, if you keep positive and optimistic about what can be done, do work out. Hillary Clinton",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope or confidence. Helen Keller",
    "Remember: Every champion was once a contender that refused to give up. Rocky Balboa",
    "We are all in the gutter, but some of us are looking at the stars. Oscar Wilde",
    "I will go anywhere as long as it’s forward. David Livingston Click to tweet",
    "Positive thoughts lead to positive results. Maria V. Snyder",
    "Create explosive confidence. Robin Sharma",
    "Everyday is a second chance. Unknown (Submitted by the Wisdom Quotes Community)",
    "Walk slowly but never walk backward. Unknown",
    "On the other side of the clouds is a bright blue sky. Unknown",
    "Keep a smile on your face. Keep a spring in your step. Joel Osteen",
    "Stay positive; stay hopeful. Joel Osteen",
    "Turn every life situation into a positive one. Rhonda Byrne",
    "There is always something to be grateful for. Rhonda Byrne",
    "Miracles are born of conviction. Marianne Williamson Click to tweet",
    "Cheerfulness is the very flower of health.",
    "Light tomorrow with today. Elizabeth Barrett Browning",
    "Clear your mind of “cant”. Samuel Johnson",
    "Conviction is much more powerful than “positive thinking”. The Stoic Emperor",
    "The most important thing is to stay positive. Saku Koivu",
    "One thing at a time. Most important thing first. Start now. Caroline Webb",
    "If you tell yourself you feel fine, you will. Jodi Picoult",
    "Keep calm and keep learning. Lailah Gifty Akita",
    "I am not a product of my circumstances. I am a product of my decisions. Stephen R. Covey Click to tweet",
    "We are limited, but we can push back the borders of our limitations. Stephen R. Covey",
    "If you want it and expect it, it will be yours very soon. Esther Hicks",
    "There isn’t anything that I cannot be or do or have. Abraham Hicks",
    "The beginning is the most important part of any work. Plato",
    "Stay positive. Forgive others. Invest in yourself. Trust your instincts. Lead with an open heart. Don’t let others ruin your day. Do things that bring you joy. Be of service to humanity. Find your soul tribe. Love yourself. Lewis Howes",
    "It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent. Madeleine Albright",
    "First say to yourself what you would be; and then do what you have to do. Epictetus Click to tweet",
    "Few things in the world are more powerful than a positive push. A smile. A world of optimism and hope. A ‘you can do it’ when things are tough. Richard M. DeVos",
    "Being relaxed, at peace with yourself, confident, emotionally neutral loose, and free-floating – these are the keys to successful performance in almost everything. Wayne Dyer",
    "Everywhere you go, make positive deposits rather than negative withdrawals. You can be a people builder. Joel Osteen",
    "Feed your inner person encouraging things that build you up and cause you to be positive, hopeful and, inspired. Joel Osteen",
    "A little progress each day adds up to big results. Unknown",
    "Sometimes the bad things that happen in our lives put us directly on the path to the best things that will ever happen to us. Unknown",
    "Keep away from people who try to belittle your ambitions. Small people always do that, but the really great makes you feel that you, too, can become great. Mark Twain",
    "You have the power to be excellent. To inspire everyone who intersects your path. To innovate and make things better than ever before. To wow customers. And to stand for the best. Will you? Robin Sharma",
    "We must accept finite disappointment, but never lose infinite hope. Martin Luther King Jr",
    "This very day can be the first day of your new life. Robin Sharma",
    "The most beautiful people I’ve known are those who have known trials, have known struggles, have known loss, and have found their way out of the depths. Elisabeth Kübler-Ross",
    "You’re stronger than you know. You’re braver than you’ve been told. You’re greater than you’ll ever imagine. Robin Sharma",
    "Positive thinking is empowering, positive action is achieving. Dr T.P.Chia.",
    "The road to success is always under construction. Lily Tomlin",
    "Let’s make positivity louder. Gary Vaynerchuk",
    "Fall seven times, stand up eight. Japanese proverb",
    "All you really need is love, but a little chocolate now and then doesn’t hurt. Charlie Brown Click to tweet",
    "Learn from yesterday, live for today, look to tomorrow, rest this afternoon. Charlie Brown",
    "There is no angry way to say bubbles. Unknown",
    "Big shots are only little shots who keep shooting. Christopher Morley",
    "If you can’t be positive, at least stay quiet. Joel Osteen",
    "Spring is nature’s way of saying, ‘Let’s party!’. Robin Williams",
    "Let peace be your middle name. Ntathu Allen Click to tweet",
    "A positive attitude may not solve all your problems, but it will annoy enough people to make it worth the effort. Herm Albright",
    "You can’t stop the waves, but you can learn how to surf. Jon Kabat-Zinn",
    "A strong positive mental attitude will create more miracles than any wonder drug. Patricia Neal",
    "People say nothing is impossible, but I do nothing every day. A.A. Milne (Winnie The Pooh)",
    "The great majority of men are bundles of beginnings. Ralph Waldo Emerson Click to tweet",
    "You are joy, looking for a way to express. Esther Hicks",
    "The energy of the mind is the essence of life. Aristotle",
    "Of the 35000 decisions you make each day, how many are positive? Negative? Fear based? Love based? Maxime Lagacé",
    "You reap fruit from the same kind of seed you’ve been sowing. You can’t talk negative and expect to live positive. Joel Osteen",
    "Positive thoughts are not enough. There have to be positive feelings and positive actions. Kamari aka Lyrikal",
    "Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky. Rabindranath Tagore",
    "You cannot tailor-make the situations in life but you can tailor-make the attitudes to fit those situations. Zig Ziglar",
    "Things turn out best for the people who make the best of the way things turn out. John Wooden",
    "Your positivity can become a castle around you which will protect you from the arrow of negativity. Gurudev Shree Chitrabhanu",
    "Your happiness can not be taken by the others if it is not given by the others. Osho",
    "Do not pray for an easy life, pray for the strength to endure a difficult one. Bruce Lee",
    "It only ends once. Anything that happens before that is just progress. Jacob (Lost)",
    "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. Henry Ford",
    "There is some good in this world, and it’s worth fighting for. J.R.R. Tolkien Click to tweet",
    "The harder the struggle, the more glorious the triumph. Self-realization demands very great struggle. Swami Sivananda",
    "For a tree to become tall it must grow tough roots among the rocks. Friedrich Nietzsche",
    "Do not let what you cannot do interfere with what you can do. John Wooden",
    "All bad things, like good things, must end. Nihar Sharma",
    "One joy scatters a hundred griefs. Chinese proverb Click to tweet",
    "One may go a long way after one is tired. French proverb",
    "Be happy. It’s one way of being wise. Colette",
    "Sometimes the best thing you can do is not think, not wonder, not imagine, not obsess. Just breathe, and have faith that everything will work out for the best. Unknown",
    "Take time to deliberate; but when the time for action arrives, stop thinking and go in. Andrew Jackson",
    "If you are positive, you’ll see opportunities instead of obstacles. Widad Akrawi",
    "Never let anyone to tell you that you need to be positive all the time; you are not a robot. Paulo Coelho",
    "Optimism is the most important human trait, because it allows us to evolve our ideas, to improve our situation, and to hope for a better tomorrow. Seth Godin",
    "Accept the fact that all events occur for a reason, and that it is within your capacity to see this reason as positive. Robert Greene",
    "The gem cannot be polished without friction, nor man perfected without trials. Chinese proverb",
    "Better to be an optimist who gets disappointed than a pessimist who has no hope. Robin Sharma",
    "Faith is having a positive attitude about what you can do and not worrying at all about what you can’t do. Joyce Meyer",
    "I do not try to dance better than anyone else. I only try to dance better than myself. Arianna Huffington Click to tweet",
    "Stay positive, all other choices are pointless punishments to your psyche. Joe Peterson",
    "No matter what the situation, remind yourself “I have a choice”. Deepak Chopra",
    "Positive thinking must be followed by positive doing. John C. Maxwell",
    "Delete the negative; accentuate the positive. Donna Karan",
    "I will heighten my life by helping others heighten theirs. Les Brown Click to tweet",
    "Prepare to win the night before. Robin Sharma",
    "Life is tough, my darling, but so are you. Stephanie Bennett-Henry",
    "I am learning to trust the journey even when I do not understand it. Mila Bron",
    "Never stop doing your best just because someone doesn’t give you credit. Unknown",
    "A big part of being a well-adjusted person is accepting that you can’t be good at everything. Kelly Williams Brown",
    "He is richest who is content with the least, for contentment is the wealth of nature. Socrates",
    "Hold on to your dreams of a better life and stay committed to striving to realize it. Earl G. Graves Sr",
    "You’ll have true happiness, true fulfillment, when you live to give, not live to get. Joel Osteen",
    "I really do believe I have everything I need to live a victorious life. I don’t always feel like it or act like it, but I believe it. Joyce Meyer",
    "Positive thinking and visualizing my success were my keys to doing well. Robert T. Kiyosaki",
    "The most successful people in life are the ones who ask questions. They’re always learning. They’re always growing. They’re always pushing. Robert T. Kiyosaki",
    "Life is not accumulation, it’s about contribution. Stephen R. Covey Click to tweet",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. David Brinkley",
    "I feel on top of the world, I feel incredible, I feel motivated, I feel empowered. I am the master of my own destiny. Maria Menounos",
    "Talk health, happiness, and prosperity to every person you meet. Christian D. Larson",
    "Work hard, stay positive, and get up early. It’s the best part of the day. George Allen",
    "We would accomplish many more things if we did not think of them as impossible. Vince Lombardi",
    "Success is the sum of small efforts, repeated day-in and day-out. Robert Collier",
    "It will work if you forget all the reasons it will not. Paulo Coelho",
    "Expect problems and eat them for breakfast. Alfred A. Montapert Click to tweet",
    "Happiness is anyone and anything that’s loved by you. Charlie Brown",
    "Why should I be unhappy? Every parcel of my being is in full bloom. Rumi",
    "The cleverest of all, in my opinion, is the man who calls himself a fool at least once a month. Fyodor Dostoevsky",
    "The key to success is not through achievement, but through enthusiasm. Malcolm Forbes",
    "Happiness is having a large, loving, caring, close-knit family in another city. George Burns",
    "As you proceed through life, following your own path, birds will shit on you. Don’t bother to brush it off. Getting a comedic view of your situation gives you spiritual distance. Having a sense of humor saves you. Joseph Campbell",
    "Happiness does not depend on your circumstances. It’s a choice that you make. Joel Osteen",
    "Be generous with your compliments and stingy with your complaints. Withhold the negative; express the positive. Joel Osteen",
    "Gratitude brings you more deeply into the present moment. Eckhart Tolle",
    "A good laugh overcomes more difficulties and dissipates more dark clouds than any other one thing. Laura Ingalls Wilder",
    "The best ideas come as jokes. Make your thinking as funny as possible. David Ogilvy",
    "Do more things that make you forget to check your phone. Unknown (See also: simplicity quotes)",
    "You will never have this day again so make it count. Unknown",
    "Plan a day that makes you jump out of bed in the morning. Unknown",
    "The secret to happiness is letting every situation be what it is instead of what you think it should be. Unknown",
    "Life becomes easier and more beautiful when we can see the good in other people. Roy T. Bennett",
    "When you think and say “I can”, confidence and happiness will fill your entire being. Remez Sasson",
    "Frame your mind to mirth and merriment which bars a thousand harms and lengthens life. William Shakespeare",
    "Passion pushes you to learn more, create more and to create better. Best of all, it’s contagious. Robert T. Kiyosaki",
    "The way you start your day determines how well you live your day. Robin Sharma Click to tweet",
    "Hope is having a positive attitude about everything that happens in life no matter what it is. Joyce Meyer",
    "Learn how to be happy with what you have while you pursue all that you want. Jim Rohn",
    "From there to here, and here to there, funny things are everywhere. Dr. Seuss",
    "Count your blessings, not your problems. Zig Ziglar",
    "Become the most positive and enthusiastic person you know. Zig Ziglar Click to tweet",
    "Be the attitude you want to be around. Tim DeTellis",
    "Perpetual optimism is a force multiplier. Colin Powell",
    "Pessimism leads to weakness, optimism to power. William James",
    "A positive mind finds opportunity in everything. A negative mind finds fault in everything. Unknown",
    "Be gentle with yourself, you’re doing the best you can. Unknown",
    "You’re allowed to scream, you’re allowed to cry, but do not give up. Unknown",
    "Be happy not because everything is good, but because you can see the good side of everything. Unknown",
    "You must master a new way to think before you can master a new way to be. Marianne Williamson Click to tweet",
    "It’s not what happens to us but our response to what happens to us that hurts us. Stephen R. Covey",
    "Attitudes are contagious. Are yours worth catching? Dennis and Wendy Mannering",
    "Optimism refuses to believe that the road ends without options. Robert H. Schuller",
    "You can’t live a positive life thinking negative thoughts. If it’s not positive, productive or faith-filled, don’t dwell on it. Joel Osteen",
    "Positive people have made up their mind to enjoy life. They focus on the possibility—not the problem. Joel Osteen",
    "Being positive means that you will have fewer negative emotions, and even if a negative emotion arises you will be positive about it too by allowing the negative emotion to be rather than trying to push it away. Rhonda Byrne",
    "Positive thinking won’t let you do anything,but it will let you do everything better than negative thinking will. Zig Ziglar",
    "Practice being positive and exceptional so much that you just can’t be negative and average ever again. Robin Sharma",
    "A positive attitude gives you power over your circumstances instead of your circumstances having power over you. Joyce Meyer",
    "Stay positive in every situation and everything you do, never stop trying, have faith don’t stop due to failure. Anurag Prakash Ray",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. Marcus Aurelius",
    "As we become more and more positive and more and more joyful, by our powerful example we uplift all of those around us. Rhonda Byrne",
    "The more positive thoughts you entertain, the happier you will become. Rhonda Byrne",
    "If you don’t like the road you’re walking, start paving another one. Dolly Parton",
    "Your thinking creates your world. Robin Sharma",
    "Love is a friendship set to music. Joseph Campbell Click to tweet",
    "The art of love is largely the art of persistence. Albert Ellis",
    "The moment we begin to seek love, love begins to seek us. And to save us. Paul Coelho",
    "Associate yourself with men of good quality if you esteem your own reputation; for ’tis better to be alone than in bad company. George Washington",
    "Love in its essence is spiritual fire. Seneca",
    "Love is a master key which opens the gate of happiness. Oliver Wedell Holmes",
    "Surround yourself with positive people that lift, motivate and inspire you. Joel Osteen",
    "You cannot hang out with negative people and expect to live a positive life. Joel Osteen",
    "Don’t brood. Get on with living and loving. You don’t have forever. Leo Buscaglia",
    "The positive force of love can create anything good, increase the good things, and change anything negative in your life. Rhonda Byrne",
    "The greatest gift you can ever give another person is your own happiness. Esther Hicks Click to tweet",
    "Accept yourself, love yourself, and keep moving forward. If you want to fly, you have to give up what weighs you down. Roy T. Bennett",
    "And in the end, the love you take, is equal to the love you make. Paul Mccartney",
    "I swear I couldn’t love you more than I do right now, and yet I know I will tomorrow. Leo Christopher",
    "Positive thinking is the key which unlocks the doors of the world. Samuel McChord Crothers",
    "The positive energy and love we give to others, heals our own wounds. Angie karan",
    "Let us always meet each other with smile, for the smile is the beginning of love. Mother Teresa",
    "The way to love anything is to realize that it may be lost. Gilbert K. Chesterton",
    "Be weird. Be random. Be who you are. Because you never know who would love the person you hide. C.S. Lewis",
    "At the touch of love everyone becomes a poet. Plato",
    "You create your own universe as you go along. Winston Churchill Click to tweet",
    "Imagination is everything. It is the preview of life’s coming attractions. Albert Einstein",
    "What a wonderful thought it is that some of the best days of our lives haven’t happened yet. Anne Frank",
    "The most powerful weapon on earth is the human soul on fire. Ferdinand Foch",
    "The real battle is taking place in your mind. What you are dwelling on, that’s what you’re attracting. Have a positive mindset. Joel Osteen",
    "The energy that you put out comes back to you. Eckhart Tolle",
    "When we are positive in our outlook and orientation, we tend to attract positive people and positive events and circumstances. Rhonda Byrne",
    "Every single second is an opportunity to change your life, because in any moment you can change the way you feel. Rhonda Byrne",
    "Hope is a positive expectation that something good is going to happen. Joyce Meyer",
    "No matter how small you start, always dream big. Stephen Richards",
    "Don’t just “hope” for a positive breakthrough; absolutely know it’s on the way. Marianne Williamson",
    "Imagine the most outrageously positive possibility for your life, claim it and consider it done. Marianne Williamson",
    "Whatever the mind can conceive it can achieve. W. Clement Stone",
    "When you are joyful, when you say yes to life and have fun and project positivity all around you, you become a sun in the center of every constellation, and people want to be near you. Shannon L. Alder",
    "Think the thought until you believe it, and once you believe it, it is. Abraham Hicks Click to tweet",
    "To bring anything into your life, imagine that it’s already there. Richard Bach",
    "The entire universe is a great theatre of mirrors. Alice Bailey",
    "Nurture your mind with great thoughts, for you will never go any higher than you think. Benjamin Disraeli",
    "Affirm the positive, visualize the positive and expect the positive, and your life will change accordingly.Remez Sasson",
    "I believe in Karma. If the good is sown, the good is collected. When positive things are made, that returns well. Yannick Noah",
    "Always believe that something wonderful is about to happen. Sukhraj S. Dhillon",
    "Have great hopes and dare to go all out for them. Have great dreams and dare to live them. Have tremendous expectations and believe in them. Norman Vincent Peale",
    "There’s a direct correlation between positive energy and positive results. Joe Rogan",
    "To attract positive energy in your life, be positive in thoughts and action. Anil Sinha",
    "Genius is the ability to receive from the universe. I Ching",
    "If you can dream it, you can do it. Walt Disney",
    "Defeat is simply a signal to press onward. Helen Keller Click to tweet",
    "If there is no struggle, there is no progress. Frederick Douglass",
    "You never know how strong you are, until being strong is your only choice. Bob Marley",
    "Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength. Arnold Schwarzenegger",
    "You don’t have to be positive all the time. It’s perfectly okay to feel sad, angry, annoyed, frustrated, scared, or anxious. Having feelings doesn’t make you a ‘negative person’. It makes you human. Lori Deschesne",
    "If you realized how powerful your thoughts are, you would never think a negative thought. Peace Pilgrim",
    "To expect defeat is nine-tenths of defeat itself. Francis Crawford",
    "Uncertainty is where things happen. It is where the opportunities — for success, for happiness, for really living — are waiting. Oliver Burkeman",
    "Every negative situation contains the possibility for something positive, an opportunity. It is how you look at it that matters. Robert Greene",
    "Something beautiful can happen to people when their world falls apart: humility, nobility and wisdom emerge just when our knees hit the floor. Marianne Williamson",
    "Anyone can hide. Facing up to things, working through them, that’s what makes you strong. Sarah Dessen",
    "Beautiful things happen when you distance yourself from negativity. Unknown",
    "Sometimes things have to go very wrong before they can be right. Unknown",
    "Relax, breathe, and roll with it. Unknown",
    "Your past mistakes are meant to guide you not define you. Unknown",
    "Be strong because things will get better. It may be stormy now but it never rains forever. Evan Carmichael",
    "Optimism is joyful searching; pessimism is a prison of fear and a clutching at illusionary safety. Kathleen A. Brehony",
    "There are some things you learn best in calm, and some in storm. Willa Cather Click to tweet",
    "Dwelling on the negative simply contributes to its power. Shirley MacLaine",
    "To find happiness, quit focusing on what’s wrong with you and start focusing on what’s right with you. Joel Osteen",
    "When you fill your life with positive thoughts and feelings, you’ll find that guilt, resentment, and any negative feelings will leave you. Rhonda Byrne",
    "Hope is important because it can make the present moment less difficult to bear. If we believe that tomorrow will be better, we can bear a hardship today. Thich Nhat Hanh",
    "It is said that the darkest hour of the night comes just before the dawn. Thomas Fuller",
    "The greatest griefs are those we cause ourselves. Sophocles",
    "Negativity is cannibalistic. The more you feed it, the bigger and stronger it grows. Bobby Darnell",
    "Do not consider painful what is good for you. Euripides",
    "Find a place inside where there’s joy, and the joy will burn out the pain. Joseph Campbell",
    "Pleasure in the job puts perfection in the work. Aristotle Click to tweet",
    "All happiness depends on courage and work. Honoré de Balzac",
    "The harder you work, the luckier you get. Mike Adenuga",
    "People who are crazy enough to think they can change the world, are the ones who do. Steve Jobs",
    "All you need is the plan, the road map, and the courage to press on to your destination. Earl Nightingale",
    "Your smile is your logo, your personality is your business card, how you leave others feeling after having an experience with you becomes your trademark. Jay Danzie",
    "To build a successful business, you must start small and dream big. In the journey of entrepreneurship, tenacity of purpose is supreme. Aliko Dangote",
    "Small opportunities are often the beginning of great enterprises. Demosthenes",
    "Work banishes those three great evils, boredom, vice, and poverty. Voltaire",
    "Laziness may appear attractive, but work gives satisfaction. Anne Frank",
    "A positive attitude will have positive results because attitudes are contagious. Zig Ziglar",
    "A diamond is a chunk of coal that did well under pressure. Unknown",
    "How hard you work matters more than how much you make. Michelle Obama",
    "The more you drive positive change, the more enhanced your business model. Anand Mahindra",
    "When you are inspired in your work, everything seems to fall into place. Wayne Dyer",
    "Our work is the presentation of our capabilities. Johann Wolfgang von Goethe Click to tweet",
    "You’ve achieved success in your field when you don’t know whether what you’re doing is work or play. Warren Beatty",
    "Real success is finding your lifework in the work that you love. David McCullough",
    "We get what we want when we stay focused and do the work. Barbara Lucas",
    "An attitude of positive expectation is the mark of the superior personality. Brian Tracy",
    "A man succeeds in completing a work only when his qualities transcend that work. Cesare Pavese",
    "There is virtue in work and there is virtue in rest. Use both and overlook neither. Alan Cohen",
    "Nothing worthwhile comes easily. Work, continuous work and hard work, is the only way to accomplish results that last. Hamilton Holt",
    "Remember, work, well done, does good to the man who does it. It makes him a better man. George S. Clason",
    "If you love your work, if you enjoy it, you’re already a success. Jack Canfield",
    "You are never too old to set another goal or to dream a new dream. C.S. Lewis",
    "Work hard at work worth doing. Theodore Roosevelt",
    "You reach a point where you don’t work for money. Walt Disney",
    "Change is inevitable. Growth is optional. John C. Maxwell Click to tweet",
    "Today’s a great day to change a life. Starting with yours. Robin Sharma",
    "Change is hard at first, messy in the middle and gorgeous at the end. Robin Sharma",
    "The greatest discovery of all time is that a person can change his future by merely changing his attitude. Oprah Winfrey",
    "Change is a part of life. Sometimes it’s positive, and other times less so. But regardless of what form it comes in, you have a choice: you can either ride the wave of change, or let it crash upon you as you struggle to remain afloat. Tony Robbins",
    "You cannot change reality, but you can control the manner in which you look at things. Your attitude is under your own control. Weed out the negative and focus on the positive. Helen Steiner Rice",
    "We are responsible for what we are, and whatever we wish ourselves to be, we have the power to make ourselves. Swami Vivekananda",
    "Instead of hating, I have chosen to forgive and spend all of my positive energy on changing the world. Camryn Manheim",
    "We cannot become what we want to be by remaining what we are. Max DePree",
    "It only takes one person to change your life: You. Ruth Casey",
    "Every great change is preceded by chaos. Deepak Chopra",
    "Times and conditions change so rapidly that we must keep our aim constantly focused on the future. Walt Disney",
    "The measure of intelligence is the ability to change. Albert Einstein Click to tweet",
    "One child, one teacher, one pen, and one book can change the world. Malala Yousafzai",
    "I truly believe the intention of creating positive change is so important to the collective consciousness. When you have a group of people that have the intention and the capacity, talent, and intelligence to actualize those intentions, then you have something really powerful. Jimmy Chin",
    "Your life does not get better by chance, it gets better by change. Jim Rohn",
    "The world is more malleable than you think and it’s waiting for you to hammer it into shape. Bono",
    "Don’t be afraid to give up the good to go for the great. John D. Rockefeller",
    "You are one decision away from a totally different life. Mark Batterson",
    "Why fit in when you were born to stand out? Dr. Seuss Click to tweet",
    "Kid, you’ll move mountains! Today is your day! Your mountain is waiting, so get on your way! Dr. Seuss",
    "Difficult roads often lead to beautiful destinations. Zig Ziglar",
    "If you fell down yesterday, stand up today. H.G. Wells",
    "We all can dance when we find music we love. Giles Andreae",
    "Do what you can, with what you have, where you are. Theodore Roosevelt",
    "You’re braver than you believe, and stronger than you seem, and smarter than you think. A.A. Milne (Winnie The Pooh)",
    "When you have a positive mindset, you can’t be defeated. No matter what comes your way, shake it off and move forward. Joel Osteen",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. Roy T. Bennett",
    "Do what is right, not what is easy nor what is popular. Roy T. Bennett",
    "Don’t let what you can’t do stop you from doing what you can do. John Wooden",
    "It’s not what happens to you, but how you react to it that matters. Epictetus",
    "The dreamers are the saviors of the world. James Allen Click to tweet",
    "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path. Buddha",
    "While we may not be able to control all that happens to us, we can control what happens inside us. Benjamin Franklin",
    "Inside of a ring or out, ain’t nothing wrong with going down. It’s staying down that’s wrong. Muhammad Ali",
    "Surround yourself with positive people and situations, and avoid negativity. Doreen Virtue",
    "Build upon strengths, and weaknesses will gradually take care of themselves. Joyce C. Lock",
    "If you have a positive attitude and constantly strive to give your best effort, eventually you will overcome your immediate problems and find you are ready for greater challenges. Pat Riley",
    "Life’s challenges are not supposed to paralyze you, they’re supposed to help you discover who you are. Bernice Johnson Reagon",
    "Instead of worrying about what you cannot control, shift your energy to what you can create. Roy T. Bennett",
    "Take responsibility of your own happiness, never put it in other people’s hands. Roy T. Bennett",
    "If I persist long enough I will win. Og Mandino Click to tweet",
    "Focus on your potential instead of your limitations. Alan Loy McGinnis",
    "The only place where your dream becomes impossible is in your own thinking. Robert H Schuller",
    "Virtually nothing is impossible in this world if you just put your mind to it and maintain a positive attitude. Lou Holtz",
    "Our beliefs about what we are and what we can be precisely determine what we can be. Tony Robbins",
    "The only way of discovering the limits of the possible is to venture a little way past them into the impossible. Arthur C. Clarke",
    "Facing it, always facing it, that’s the way to get through. Face it. Joseph Conrad",
    "Discouragement and failure are two of the surest stepping stones to success. Dale Carnegie",
    "Make improvements, not excuses. Seek respect, not attention. Roy T. Bennett",
    "When the going gets tough, the tough get going. Joseph Kennedy",
    "The question isn’t who’s going to let me; it’s who is going to stop me. Ayn Rand Click to tweet",
    "You may have to fight a battle more than once to win it. Margaret Thatcher",
    "Just because you fail once doesn’t mean you’re gonna fail at everything. Marilyn Monroe",
    "Start each day with a positive thought and a grateful heart. Roy T. Bennett",
    "Your energy is contagious, so think about what you want people to catch from you. Marie Forleo",
    "There is a truth deep down inside of you that has been waiting for you to discover it, and that truth is this: you deserve all good things life has to offer. Rhonda Byrne",
    "She needed hero, so she became one. Unknown",
    "Positive thoughts = Positive life. Mel Robbins",
    "There’s power in looking silly and not caring that you do. Amy Poehler",
    "Change the way you look at things and the things you look at change. Wayne W. Dyer",
    "Keep your face towards the sunshine and shadows will fall behind you. Walt Whitman Click to tweet"
  ]

  export default quotes;